#!/bin/bash
echo Use .env file to read sensitive information
while IPS='=' read -r key _; do
    eval "${key}"
done <'.env'

# SEARCH_PATTERN=mast.eu.spb.ru/phytonium:v1${DOCKER_TAG_SUFFIX}
DOCKER_COMPOSE_NETWORK_PREFIX="${PWD##*/}"
# DOCKER_COMPOSE_NETWORK=${DOCKER_COMPOSE_NETWORK_PREFIX}_default
SERVICE_NAME=${DOCKER_COMPOSE_NETWORK_PREFIX}-front-1

docker exec -it "$(docker container ls | grep "${SERVICE_NAME}" | awk ' { print $1 } ')" sh
